### ISSUE TITLE
Eksempler?

### ISSUE THREAD

**Issue by boelle** [GylleTanken/python-danfoss-eco-2#1]
Kunne du evt tilføje nogen eksempler hvordan man bruger dit script?

jeg har lige opdaget de her eco2 ventiler og det man kan forbinde med bluetooth letter arbejdet end del, havde ellers planlagt at bruge telestater med det bøvl der følger med

det jeg har brug for er at kunne sætte target samt hive data ud af ventilen

og for at kunne det ved jeg man skal have device id som vist nok er det samme som bluetooth mac adresse samt en encryption key, men hvordan klare man lige det?

**Comment by GylleTanken** [comment]
Jeg har tilføjet et eksempel nu, og jeg har beskrevet en metode til at finde encryption key.
